from ._constants import APP_NAME as APP_NAME
from ._constants import ASCII_ENCODING as ASCII_ENCODING
from ._constants import UTF8_ENCODING as UTF8_ENCODING
from ._constants import DEFAULT_IP as DEFAULT_IP
from ._constants import DEFAULT_WEB_PORT as DEFAULT_WEB_PORT
from ._constants import POST as POST
from ._constants import GET as GET
from ._constants import MOVIE_SOURCES as MOVIE_SOURCES
from ._constants import SECRET_KEY as SECRET_KEY
from ._constants import JSON_INDENT as JSON_INDENT
